### PR TITLE
Gzweb support

### PR DESCRIPTION
**Pull request by kapilPython**
*Issue #, if available:*
Adding Gzweb Support

*Description of changes:*
1) change of all model.sdf files to make it compatible to gzweb, the changes still work with gazebo and ros.
2) Added changes to README to allow use of the models with Gzweb.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ahtsan** [comment]
Have you encountered GZWeb only showing collisions but not meshes?
image

**Comment by kapilPython** [comment]
https://github.com/aws-robotics/aws-robomaker-small-warehouse-world/blob/5bade00a4257c8b92e8a9d4fb53e986779b95be3/models/aws_robomaker_warehouse_Bucket_01/meshes/aws_robomaker_warehouse_Bucket_01_visual.DAE#L5

Lets take this issue with the above example in the visual.DAE file the <init_from> tag gets deleted after running the deploy script of gzweb, it is their bug and therefore the http page is unable to find the texture images and therefore unable to create visual effect for all the collisions available.

Now, to run warehouse models in gzweb there are two ways:
1) Traditional - running the deploy script by giving path to local models (for this I am pushing an update to this pull request)
2) Directly copying all the models to the ~/gzweb/http/client/assets folder (this works without problem with current commit on the pull request)

Now, I have tried running the deploy script with coarse option which makes models smaller and makes the rendering possible on  mobile devices too and it works fine too.

**Comment by ahtsan** [comment]
> https://github.com/aws-robotics/aws-robomaker-small-warehouse-world/blob/5bade00a4257c8b92e8a9d4fb53e986779b95be3/models/aws_robomaker_warehouse_Bucket_01/meshes/aws_robomaker_warehouse_Bucket_01_visual.DAE#L5
> 
> Lets take this issue with the above example in the visual.DAE file the <init_from> tag gets deleted after running the deploy script of gzweb, it is their bug and therefore the http page is unable to find the texture images and therefore unable to create visual effect for all the collisions available.
> 
> Now, to run warehouse models in gzweb there are two ways:
> 
> 1. Traditional - running the deploy script by giving path to local models (for this I am pushing an update to this pull request)
> 2. Directly copying all the models to the ~/gzweb/http/client/assets folder (this works without problem with current commit on the pull request)
> 
> Now, I have tried running the deploy script with coarse option which makes models smaller and makes the rendering possible on mobile devices too and it works fine too.

That's surprising. Thanks for pointing that out. Do you have a reference for their bug? e.g. url to their github file?

Also, could you elaborate on the first way (Traditional)? Do you mean there's a way to have it working and we don't have to copy the assets to ~/gzweb/http/client/assets folder?

**Comment by ahtsan** [comment]
ah, I see what you meant.

In a terminal A, run
```
cd aws-robomaker-small-warehouse-world
export GAZEBO_MODEL_PATH=`pwd`/models
gzserver worlds/small_warehouse.world
```

and in another terminal, run

```

cd aws-robomaker-small-warehouse-world
export GAZEBO_MODEL_PATH=`pwd`/models
# install gzweb following http://gazebosim.org/gzweb.html#install-collapse-1
cd ~/gzweb
npm run deploy --- -m local
npm start
```

I verified this to be working with melodic + Gazebo 9.

**Comment by ahtsan** [comment]
Overall it looks good, I'll do a bit more testing on other ROS distro and make some modification to the README.
Thank you for you contribution!

**Comment by ahtsan** [comment]
@kapilPython Which distro did you test and what's your node version? From my testing v8.11.3 works for Melodic but I haven't been able to find a working version for Kinetic.

**Comment by ahtsan** [comment]
@kapilPython I've made some changes to the README.

**Review by ojasjoshi — APPROVED** [review]

**Review by mm318 — APPROVED** [review]

**Pull request merged**
